#                                    __   __  __
#                                    \ \ / / / /
#                                     \ V / / /
#                                      \_/  \/
#
#                                    V E C T O R
#                                   Configuration
#
# ------------------------------------------------------------------------------
# Website: https://vector.dev
# Docs: https://vector.dev/docs
# Chat: https://chat.vector.dev
# ------------------------------------------------------------------------------

# Change this to use a non-default directory for Vector data storage:
data_dir = "./vector-data"

[sources.heroku_log_plex]
type = "heroku_logs"
address = "0.0.0.0:${PORT}"
query_parameters = ["service", "env", "heroku_app_name"]

[transforms.heroku]
type = "route"
inputs = ["heroku_log_plex"]
  [transforms.heroku.route]
  app = '.app_name == "app"'
  router = '.app_name == "heroku"'

[transforms.heroku_router_logfmt]
type = "remap"
inputs = ["heroku.router"]
source = '''
. = merge(., parse_logfmt!(string!(.message)))
del(.message)
'''

[transforms.heroku_app_json]
type = "remap"
inputs = ["heroku.app"]
source = '''
. = merge!(., parse_json!(string!(.message)))
del(.message)
'''

[sinks.print]
type = "console"
inputs = [ "heroku_router_logfmt", "heroku_app_json" ]
target = "stdout"
encoding.codec = "json"

